export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const OPEN_REGISTER = 'OPEN_REGISTER';

export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
